services:
  web:
    platform: linux/arm64
    build: 
      context: .
      platforms:
        - linux/arm64
    env_file:
      - .env
    depends_on:
      - mariadb
    extra_hosts:
      - "1up-keycloak.localhost:${DOCKER_HOST_GATEWAY_IP:-host-gateway}"
    volumes:
      - ./conf:/workspace
      - ./conf/ilias.json:/var/www/config/ilias.json:ro
      - ./scripts:/opt/1upilias/scripts:ro
      - ./src:/var/www/ilias
      - ilias_files:/var/www/files
      - ilias_logs:/var/www/logs
    ports:
      - "${ILIAS_PORT:-28084}:80"
    networks:
      - internal
    restart: unless-stopped


  mariadb:
    image: mariadb:10.6.18
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=ilias
    command:
      - --innodb_buffer_pool_size=8G
      - --character_set_server=utf8
      - --collation_server=utf8mb3_general_ci
    networks:
      - internal
    ports:
      - "127.0.0.1:${MARIADB_PORT:-28306}:3306"
    volumes:
      - ilias_mariadb_data:/var/lib/mysql
    restart: unless-stopped


networks:
  internal:
    driver: bridge

volumes:
  ilias_mariadb_data:
  ilias_files:
  ilias_logs:
